name: CodeQL Analysis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  analyze:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - language: c-cpp
            build-mode: manual
          # - language: csharp
          #   build-mode: autobuild
          # - language: java-kotlin
          #   build-mode: none

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - if: ${{ matrix.build-mode == 'manual' }}
        name: Build C and C++ code
        run: |
          echo 'If you are using a "manual" build mode for one or more of the' \
            'languages you are analyzing, replace this with the commands to build' \
            'your code, for example:'
          echo ' make bootstrap'
          echo ' make release'
          exit 1

    # Add more steps as needed for your workflow
