name: CodeQL Analysis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  analyze:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - language: c-cpp
            build-mode: manual

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - if: ${{ matrix.build-mode == 'manual' }}
        name: Build C and C++ code
        run: |
          echo "Building C++ snippets..."
          for file in *.cpp; do
            echo "Compiling $file"
            clang++ -c "$file" -o /dev/null
          done

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
