name: Codevul CodeQL Analysis
# Grant the necessary permissions to upload SARIF results.
permissions:
  actions: read
  contents: read
  security-events: write

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  analyze:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - language: c-cpp
            build-mode: manual

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      # Manual build step to compile your snippets (adjust as needed).
      - if: ${{ matrix.build-mode == 'manual' }}
        name: Build C/C++ code
        run: |
          echo "Building C++ snippets..."
          for file in *.cpp; do
            echo "Compiling $file"
            clang++ -c "$file" -o /dev/null -include dummy_defs.h || true
          done

      # Workaround step: Create the missing tarballs directory.
      - name: Create empty tarballs directory
        run: |
          mkdir -p /home/runner/work/_temp/codeql_databases/cpp/trap/cpp/tarballs

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
